### ISSUE TITLE
Make "scrollSpy" a bit more precise.

### ISSUE THREAD

**Issue by levsthings** [monolambda/monolambda#3]
_After our page is finished..._

## 👾 Goals: 👾 
- [ ] Make offset values of scrollSpy precise (this includes highlighting all sections despite the display of the length of the page on various devices)
- [ ] Add a small CSS transition effect to highlighted navbar items
- [ ] Review CTA break - to highlight? Or not to highlight?
- [ ] Review/change highlighting nav item color (active, hover, etc)
_In Edge, highlighting nav turns white on scroll. This has to do with the current gradient placeholder_

Look into different implementations, using a light-weight vanilla JS library for more precision:
https://github.com/forsigner/scroll-spy/tree/master/lib
https://www.npmjs.com/package/scroll-spy

**Comment by levsthings** [comment]
After playing with offset values, another point of improvement that'll create a better flow for `scrollSpy` might be achieved via adding a small CSS transition effect to highlighted navbar items. Right now, we don't have any delay so `scrollSpy` is acting very sharp while moving between sections.

**Comment by JavaScriptErika** [comment]
We also need to review our `CTA parallax break` that's right below `services`. Do we want that section to be included in highlighting our 'Services' nav item? It is a part of services, but it can stand alone. This should be reviewed when the page is complete so we can get a full overview of the look and feel.

**Comment by JavaScriptErika** [comment]
Initial comment updated
