### ISSUE TITLE
Partners Hotjar icon has extra 'pixels' underneath

### ISSUE THREAD

**Issue by JavaScriptErika** [monolambda/monolambda#31]
In the Brave browser, Hotjar has a glitch where extra 'pixel-like' residue appears underneath it. The residue disappears and reappears as well. 
Marked as a minor bug since this is not a major browser.
![hotjar](https://user-images.githubusercontent.com/19316487/29591588-5dcdcacc-876d-11e7-8700-6ef03675cc14.PNG)

**Comment by levsthings** [comment]
![hotjar](https://user-images.githubusercontent.com/20170364/29612206-1c3eee6e-8809-11e7-807c-5ce8701ebbd7.png)
The SVG is fine, most likely an issue of Brave, we should only file bugs for major browsers.
