### ISSUE TITLE
Mobile menu doesn't push down hero far enough

### ISSUE THREAD

**Issue by JavaScriptErika** [monolambda/monolambda#36]
Tested on Android mobile device via Firefox and Chrome browsers. Edge has not been tested.

Expanded hamburger menu does not push down our monoLambda title / hero down far enough, and cuts off "We Are".

Works with plenty of margin in tablet views (tested in FF).

![mobile1](https://user-images.githubusercontent.com/19316487/29650677-782ffaa4-886a-11e7-9f06-1b6cb09396ed.jpg)

**Comment by levsthings** [comment]
Good catch, I think we can squeeze it in to #33 since it's still a navBar thing.

**Comment by levsthings** [comment]
We decided that this will be fixed in a new PR.
