### ISSUE TITLE
Firefox Tablet: rocket icon does not show after form is submitted

### ISSUE THREAD

**Issue by JavaScriptErika** [monolambda/monolambda#39]
After a form has been successfully submitted, the rocket icon does not appear on tablet devices using Firefox browser.

The other browsers that were able to be tested in tablet view include Chrome.  Edge has not been tested.

**Comment by levsthings** [comment]
"Firefox Tablet" is a very wide category. The Issue message needs to be edited with the information:

Firefox version
OS/Version
