### ISSUE TITLE
Improve dynamic hero messages

### ISSUE THREAD

**Issue by levsthings** [monolambda/monolambda#6]
Part of our hero messages are dynamically changing, adding an animation to these messages so that they will have a mechanical counter animation would be good.

**Comment by JavaScriptErika** [comment]
The messages dynamically changing in mobile view causes other divs to jump when the messages go from one to two lines, and vice versa.

**Comment by levsthings** [comment]
Good call, I'm aware of this problem. This is merely because we haven't set a breakpoint to decrease the size of the hero font-sizes. They are too big for mobile, we'll add a media query for them in the polish stage.
